version: 2
jobs:
  job_build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            make init
      - run:
          name: run unit tests
          command: |
            make unit_test
      - run:
          name: run lint
          command: |
            make lint

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - job_build
      - job_deploy:
          requires:
            - job_build
          filters:
            branches:
              only: master
